version: '3'
services:
  browserless:
    image: browserless/chrome
    ports:
      - "3000:3000"
    environment:
      - DEBUG=browserless/chrome
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=600000
      - MAX_QUEUE_LENGTH=10
      - ENABLE_CORS=true
      - CHROME_REFRESH_TIME=3600000
    shm_size: 2gb
    restart: always